name: CMake

on:
  push:
    branches: [ "experiment/build_gtk_on_gh" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:23.04

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        apt-get update && apt-get -y install \
        cmake \
        build-essential \
        g++ \
        gcc \
        libgtkmm-4.0-dev \
        libusb-1.0-0-dev \
        libssl-dev \

    - name: apt cleanup
      run: |
        apt autoclean && rm -rf /var/lib/apt/lists/*

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build cli
      run: cmake --build ${{github.workspace}}/build --config=${{env.BUILD_TYPE}} --target authpp

    - name: Build gtk
      run: cmake --build ${{github.workspace}}/build --config=${{env.BUILD_TYPE}} --target authppgtk

    - name: Build tests
      run: cmake --build ${{github.workspace}}/build --config=${{env.BUILD_TYPE}} --target authpp_test

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
